export const LIST_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST'
export const LIST_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS'
export const LIST_MOVIES_FAIL = 'LIST_MOVIES_FAIL'
export const LIST_MOVIES_RESET = 'LIST_MOVIES_RESET'

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL'

export const LIKE_MOVIE_REQUEST = 'LIKE_MOVIE_REQUEST'
export const LIKE_MOVIE_SUCCESS = 'LIKE_MOVIE_SUCCESS'
export const LIKE_MOVIE_FAIL = 'LIKE_MOVIE_FAIL'
export const LIKE_MOVIE_RESET = 'LIKE_MOVIE_RESET'

export const DISLIKE_MOVIE_REQUEST = ' DISLIKE_MOVIE_REQUEST'
export const DISLIKE_MOVIE_SUCCESS = ' DISLIKE_MOVIE_SUCCESS'
export const DISLIKE_MOVIE_FAIL = ' DISLIKE_MOVIE_FAIL'
export const DISLIKE_MOVIE_RESET = ' DISLIKE_MOVIE_RESET'

export const LIST_LIKED_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST'
export const LIST_LIKED_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS'
export const LIST_LIKED_MOVIES_FAIL = 'LIST_MOVIES_FAIL'

export const LIST_DISLIKED_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST'
export const LIST_DISLIKED_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS'
export const LIST_DISLIKED_MOVIES_FAIL = 'LIST_MOVIES_FAIL'

export const REMOVE_LIKE_FROM_STORAGE = 'REMOVE_LIKE_FROM_STORAGE'
export const REMOVE_DISLIKE_FROM_STORAGE = 'REMOVE_DISLIKE_FROM_STORAGE'
